fix: NameError issue with Manager._ref
Since pydantic 2.1, private attributes are not supported anymore.

This fixes this exception:

    NameError: Fields must not use names with leading underscores; e.g., use 'ref' instead of '_ref'.